# conda env create --file environment.yml
name: eda_personal_projects
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - seaborn
  - statsmodels
  - scipy
  - pandas
  - numpy
  - matplotlib
  - pip
  - pyprojroot
  - python=3.7
  - missingno
  - upsetplot
  - pip:
    - pyhere
    - pyjanitor==0.22.0
    